device: gpu

dataset_args:
  d_type: train
  dataset_path: "/data/students/louis/standfordcars/standfordcars"
  img_size: 288
  transform: 
    - resize
    - randomflip
    - randomcrop
    - tensor


model_args:
  epochs: 50
  lr: 1e-2


dataloader_args:
  num_workers: 6
  train_batch: 128
  test_batch: 32
  shuffle: True

