checkpoint_path: NONE
d_type: train
dataset: standford
dataset_path: /data/students/louis/standfordcars/standfordcars/
epochs: 25
img_size: 288
latent_dim: 384
lr: 0.01
model_paths:
- this is not a path
- ./models/CAE/CAE 16Sep16h22//model.pth
- ./models/CAE/CAE 18Sep20h02//model.pth
- ./models/CAE/CAE 18Sep23h47//model.pth
num_workers: 6
patience: 5
shuffle: true
task: reconstruction
test_batch: 32
transforms: pil,randomflip,randomflip,resize,tensor
