1&num_workers: 6
dataset: cifar10
d_type: train
dataset_path: /data/students/louis/cifar10/
device: gpu
epochs: 25
factor: 0.2
img_size: 288
latent_dim: 356
lr: 0.01
min_lr: 0.0005
mode: min
model_paths:
- this is not a path
- ./models/CAE 14Sep14h32/model.pth
- ./models/CAE 14Sep15h01/model.pth
patience: 5
shuffle: true
test_batch: 32
train_batch: 128
transforms: resize,tensor
