d_type: train
dataset_path: /data/students/louis/standfordcars/standfordcars/
device: gpu
epochs: 100
factor: 0.2
img_size: 288
latent_dim: 1000
lr: 0.01
min_lr: 0.0005
mode: min
model_paths:
- ./models/CAE 13Sep14h14/model.pth
- ./models/CAE 13Sep16h03/model.pth
- ./models/CAE 13Sep17h13/model.pth
- ./models/CAE 13Sep22h22/model.pth
- ./models/CAE 13Sep22h49/model.pth
- ./models/CAE 14Sep10h40/model.pth
num_workers: 6
patience: 5
shuffle: true
test_batch: 32
train_batch: 128
transforms: resize,tensor
