d_type: train
dataset: standford
dataset_path: /data/students/louis/standfordcars/standfordcars/
device: gpu
epochs: 250
factor: 0.2
img_size: 288
latent_dim: 356
lr: 0.01
min_lr: 0.0001
mode: min
model_paths:
- this is not a path
- ./models/CAE 14Sep20h12/model.pth
num_workers: 6
patience: 5
shuffle: true
test_batch: 32
train_batch: 8
transforms: randomflip,randomflip,resize,tensor
